/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.alejandrogarciahub.webserver;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        final WebServer classUnderTest = new WebServer();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
