/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.alejandrogarciahub.webserver;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class WebServerTest {
  @Test
  void appHasAGreeting() {
    final WebServer classUnderTest = new WebServer();
    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
  }
}
