/*
 * This source file was generated by the Gradle 'init' task
 */
package ch.alejandrogarciahub.webserver;

public class WebServer {
    public final String getGreeting() {
        return "Hello World!";
    }

    public static void main(final String[] args) {
        System.out.println(new WebServer().getGreeting());
    }
}
